# This file is based on https://github.com/immich-app/immich/blob/main/docker/docker-compose.yml
# `# *` specifies significant changed configurations. Everything else comes from the above base file.
version: "3.8"

# * added an external network
# `docker create network traefik_net` via unraid's terminal
# traefik sends incoming requests through here
networks:
  traefik_net:
    external: true

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL                                                        #  I never set these up. Not sure they're needed.
      - IMMICH_WEB_URL                                                           #  I never set these up. Not sure they're needed.
    ports:
      - 2283:8080                                                                # Map port 2283 in the container <-> 8080 on the docker host
      - 2284:443                                                                 # May not be needed (Map port 2284 in the container -> 8080 on the docker host)
    depends_on:
      - immich-server
      - immich-web
    restart: always
    networks:
      - default                                                                  # * set traefik to communicate on the immich_default network for internal traffic (immich_ is emplaced in front because it's not defined in this config's root level `networks` block)
      - traefik_net                                                              # * set traefik to communicate on the traefik_net network for incoming web requests from traefik
    labels:
      # * Borrowed these settings from https://www.reddit.com/r/selfhosted/comments/vhzep9/comment/imof04q/?utm_source=share&utm_medium=web2x&context=3
      #   specifically https://privatebin.devol.it/?3e024aa038588fc4#HmuFFDjK4e3Htu3Juu9AHwq8hQYNpbwf1LVe8jMdKEcM
      - "traefik.enable=true"                                                     # * required in order for traefik to see `immich_proxy` and talk to it.
      - "traefik.docker.network=traefik_net"                                      # might be redundant to `networks: - traefik_net`. Defines a default docker network to use for connections to all containers. 
      - "traefik.http.routers.immich_proxy.entrypoints=websecure"                 # * for `immich_proxy` to receive, traefik only listens for incoming requests on the HTTPS entrypoint
      - "traefik.http.routers.immich_proxy.tls.certresolver=myresolver"           # * resolve ssl certificates using the `myresolver` set up by traefik config's `certificatesresolvers.myresolver`
      - "traefik.http.routers.immich_proxy.rule=Host(`photos.codyduncan.net`)"    # * for `immich_proxy` to receive, only take requests for `photos.codyduncan.net` 
      - "traefik.http.services.immich_proxy.loadbalancer.server.port=8080"        # * traefik should send requests to port 8080 on the docker host. (in `ports:` this is redirected to 2283, which is the main entrypoint from the immich docs, https://documentation.immich.app/docs/developer/setup#instructions)
      # Redirect https://photos.codyduncan.net/public to a publicly shared gallery with a really long url.
      - "traefik.http.routers.immich_proxy.middlewares=publicshare-redirectregex"
      - "traefik.http.middlewares.publicshare-redirectregex.redirectregex.regex=^https://photos.codyduncan.net/public"
      - "traefik.http.middlewares.publicshare-redirectregex.redirectregex.replacement=https://photos.codyduncan.net/share/znTs0C-Nla8GS4rQ2NMFCW1R1IkPEAGNr2NJn942iuPru310VLPrQMrQpTp52Imlec4"
  
volumes:
  pgdata:
  model-cache:
  tsdata:
